services:
#    experience.example:
#        class: ExperienceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    experience.presave:
        class: ExperienceBundle\Service\ExperiencePreSave
        arguments: ["@security.token_storage"]
    experience.parameter_checker:
        class: ExperienceBundle\Service\ExperienceParameterChecker
        arguments: []