<?php

namespace ExperienceBundle\Repository;

use ExperienceBundle\Entity\ExperienceType;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
