<?php

namespace ExperienceBundle\Repository;

/**
 * ExperienceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
