<?php

namespace ExperienceBundle\Repository;

/**
 * ParameterValueFloatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterValueFloatRepository extends \Doctrine\ORM\EntityRepository
{
}
