<?php

namespace ExperienceBundle\Repository;

/**
 * ParameterValueBoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterValueBoolRepository extends \Doctrine\ORM\EntityRepository
{
}
