<?php

namespace ExperienceBundle\Repository;

/**
 * ParameterValueListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParameterValueListRepository extends \Doctrine\ORM\EntityRepository
{
}
