services:
#    tools.example:
#        class: ToolsBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    tools.file:
        class: ToolsBundle\Service\FileTool
        arguments: ["%tmp_directory%"]