<?php

namespace SpoolerBundle\Repository;

/**
 * RequestedParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestedParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
