<?php

namespace SpoolerBundle\Repository;

/**
 * ResultFilesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultFileRepository extends \Doctrine\ORM\EntityRepository
{
}
